import {
  Badge,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@weekend/design/registry";
import { CodeInline } from "../../components/code-block";
import { H } from "../../components/heading";

/**
 * Pulled at build time from `packages/design/.consumers/*.json` via Vite's
 * `import.meta.glob` (eager, default-imported). One JSON per exported symbol;
 * regenerated by `pnpm design:index`.
 */
interface ConsumerEntry {
  readonly file: string;
  readonly line: number;
  readonly props: ReadonlyArray<string>;
}

interface ConsumerJson {
  readonly symbol: string;
  readonly tier: "core" | "registry";
  readonly consumers: ReadonlyArray<ConsumerEntry>;
  readonly propUsage: Record<string, number>;
  readonly totalUsages: number;
}

const MODULES = import.meta.glob<ConsumerJson>(
  "/packages/design/.consumers/*.json",
  { eager: true, import: "default" },
) as Record<string, ConsumerJson>;

interface ConsumerRow {
  readonly symbol: string;
  readonly tier: "core" | "registry";
  readonly totalUsages: number;
  readonly topFiles: ReadonlyArray<readonly [string, number]>;
}

const ROWS: ReadonlyArray<ConsumerRow> = Object.values(MODULES)
  .filter((m): m is ConsumerJson => m !== null && typeof m === "object" && "symbol" in m)
  .map((m): ConsumerRow => {
    const fileCounts = new Map<string, number>();
    for (const c of m.consumers) {
      fileCounts.set(c.file, (fileCounts.get(c.file) ?? 0) + 1);
    }
    const topFiles = [...fileCounts.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3);
    return {
      symbol: m.symbol,
      tier: m.tier,
      totalUsages: m.totalUsages,
      topFiles,
    };
  })
  .sort((a, b) => b.totalUsages - a.totalUsages);

const TIER_COLOR = { core: "blue", registry: "violet" } as const;

const TOTALS = {
  count: ROWS.length,
  totalUsages: ROWS.reduce((acc, r) => acc + r.totalUsages, 0),
  unused: ROWS.filter((r) => r.totalUsages === 0).length,
};

function shortenFile(path: string): string {
  // Trim the common src/ prefix so the table stays readable.
  return path.replace(/^src\//, "");
}

export function PageConsumers(): React.JSX.Element {
  return (
    <>
      <header className="page-header">
        <div className="page-eyebrow">State</div>
        <h1>Consumers</h1>
        <p className="lede">
          Where every <CodeInline>@weekend/design</CodeInline> export gets used. Generated by{" "}
          <CodeInline>pnpm design:index</CodeInline>; loaded here from{" "}
          <CodeInline>packages/design/.consumers/*.json</CodeInline> at build time.
        </p>
        <div
          className="meta-row"
          style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 16 }}
        >
          <Badge color="gray">{TOTALS.count} symbols</Badge>
          <Badge color="gray">{TOTALS.totalUsages} total usages</Badge>
          {TOTALS.unused > 0 ? (
            <Badge color="amber" variant="dot">
              {TOTALS.unused} unused
            </Badge>
          ) : null}
        </div>
      </header>

      <div className="section">
        <H as="h2" id="usage">
          By usage
        </H>
        <p>
          Sorted by total usage count, descending. Top consumer files show the three call sites
          with the most occurrences — useful when sizing the blast radius of a prop deprecation.
        </p>
        <div className="example">
          <div className="example-stage" style={{ padding: 0 }}>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Symbol</TableHead>
                  <TableHead>Tier</TableHead>
                  <TableHead>Total</TableHead>
                  <TableHead>Top consumer files</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {ROWS.map((row, i) => (
                  <TableRow key={row.symbol} index={i}>
                    <TableCell>
                      <span
                        style={{
                          fontFamily: "var(--font-mono)",
                          fontSize: 12,
                          fontVariationSettings: "var(--fw-semibold)",
                        }}
                      >
                        {row.symbol}
                      </span>
                    </TableCell>
                    <TableCell>
                      <Badge color={TIER_COLOR[row.tier]} size="sm" variant="dot">
                        {row.tier}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <span
                        style={{
                          fontFamily: "var(--font-mono)",
                          fontSize: 13,
                          fontVariationSettings: "var(--fw-medium)",
                          color:
                            row.totalUsages === 0
                              ? "var(--muted-foreground)"
                              : "var(--foreground)",
                        }}
                      >
                        {row.totalUsages}
                      </span>
                    </TableCell>
                    <TableCell>
                      {row.topFiles.length === 0 ? (
                        <span style={{ fontSize: 13, color: "var(--muted-foreground)" }}>
                          —
                        </span>
                      ) : (
                        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
                          {row.topFiles.map(([file, count]) => (
                            <div
                              key={file}
                              style={{
                                fontFamily: "var(--font-mono)",
                                fontSize: 11.5,
                                color: "var(--muted-foreground)",
                                lineHeight: 1.5,
                              }}
                            >
                              <span style={{ opacity: 0.6 }}>{count}×</span> {shortenFile(file)}
                            </div>
                          ))}
                        </div>
                      )}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </div>
      </div>
    </>
  );
}
