"""Generate the Weekend wordmark React component from the Advercase TTF.

Run with a venv that has fonttools installed:
    python3 -m venv /tmp/wm-venv && /tmp/wm-venv/bin/pip install fonttools
    /tmp/wm-venv/bin/python scripts/generate-wordmark.py

The output component inlines the SVG so fill='currentColor' picks up the
theme's text color (loading via <img> would collapse it to black).
"""
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

REPO = Path(__file__).resolve().parent.parent
FONT_PATH = Path.home() / ".weekend/weekend-software-web/public/fonts/Advercase-Font-Regular.ttf"
OUT_PATH = REPO / "src/components/branding/weekend-wordmark.tsx"
TEXT = "Weekend"

font = TTFont(FONT_PATH)
glyph_set = font.getGlyphSet()
cmap = font.getBestCmap()
hmtx = font["hmtx"]
ascent = font["hhea"].ascent
descent = font["hhea"].descent
height = ascent - descent

paths = []
x = 0
for ch in TEXT:
    glyph_name = cmap[ord(ch)]
    advance, _ = hmtx[glyph_name]
    pen = SVGPathPen(glyph_set)
    glyph_set[glyph_name].draw(pen)
    d = pen.getCommands()
    if d:
        paths.append((x, d))
    x += advance
total_width = x

path_jsx = "\n      ".join(
    f'<path transform="translate({px} 0)" d={{"{d}"}} />'
    for px, d in paths
)

component = f'''// Auto-generated by scripts/generate-wordmark.py — do not edit by hand.
// Source font: Advercase-Font-Regular.ttf, text "{TEXT}".

import type {{ SVGProps }} from "react";

export function WeekendWordmark(props: SVGProps<SVGSVGElement>) {{
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 {total_width} {height}"
      fill="currentColor"
      role="img"
      aria-label="{TEXT}"
      {{...props}}
    >
      <g transform="translate(0 {ascent}) scale(1 -1)">
      {path_jsx}
      </g>
    </svg>
  );
}}
'''

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
OUT_PATH.write_text(component)
print(f"wrote {OUT_PATH.relative_to(REPO)}")
print(f"viewBox: 0 {descent} {total_width} {height} (aspect {total_width/height:.3f}:1)")
