/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedDropRouteImport } from './routes/shared-drop'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceProjectRouteImport } from './routes/workspace.$project'
import { Route as DevDsRouteImport } from './routes/dev.ds'

const SharedDropRoute = SharedDropRouteImport.update({
  id: '/shared-drop',
  path: '/shared-drop',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectRoute = WorkspaceProjectRouteImport.update({
  id: '/workspace/$project',
  path: '/workspace/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDsRoute = DevDsRouteImport.update({
  id: '/dev/ds',
  path: '/dev/ds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/shared-drop': typeof SharedDropRoute
  '/dev/ds': typeof DevDsRoute
  '/workspace/$project': typeof WorkspaceProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/shared-drop': typeof SharedDropRoute
  '/dev/ds': typeof DevDsRoute
  '/workspace/$project': typeof WorkspaceProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/home': typeof HomeRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/shared-drop': typeof SharedDropRoute
  '/dev/ds': typeof DevDsRoute
  '/workspace/$project': typeof WorkspaceProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/home'
    | '/logs'
    | '/settings'
    | '/shared'
    | '/shared-drop'
    | '/dev/ds'
    | '/workspace/$project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/home'
    | '/logs'
    | '/settings'
    | '/shared'
    | '/shared-drop'
    | '/dev/ds'
    | '/workspace/$project'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/home'
    | '/logs'
    | '/settings'
    | '/shared'
    | '/shared-drop'
    | '/dev/ds'
    | '/workspace/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  HomeRoute: typeof HomeRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  SharedDropRoute: typeof SharedDropRoute
  DevDsRoute: typeof DevDsRoute
  WorkspaceProjectRoute: typeof WorkspaceProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shared-drop': {
      id: '/shared-drop'
      path: '/shared-drop'
      fullPath: '/shared-drop'
      preLoaderRoute: typeof SharedDropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$project': {
      id: '/workspace/$project'
      path: '/workspace/$project'
      fullPath: '/workspace/$project'
      preLoaderRoute: typeof WorkspaceProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ds': {
      id: '/dev/ds'
      path: '/dev/ds'
      fullPath: '/dev/ds'
      preLoaderRoute: typeof DevDsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  HomeRoute: HomeRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  SharedDropRoute: SharedDropRoute,
  DevDsRoute: DevDsRoute,
  WorkspaceProjectRoute: WorkspaceProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
